eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
server:
  port: 8080

#  服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: study

