server:
  port: 8761

  instance:
  #  设置当前实例的主机名称
    hostname: localhost
  client:
  #  启动服务注册
    registerWithEureka: false
#    以下为true才会启用
    #    连接 Eureka Server 的超时时间，单位：秒
#        eureka-server-connect-timeout-seconds: 2
    #    读取 Eureka Server 信息的超时时间，单位：秒
#        eureka-connection-idle-timeout-seconds: 2

#    检索服务
    fetchRegistry: false
#    指定服务注册中心地址，类型为 HashMap，并设置有一组默认值，默认的Key为 defaultZone；默认的Value为 http://localhost:8761/eureka ，如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
#    如果服务注册中心加入了安全验证，这里配置的地址格式为： http://<username>:<password>@localhost:8761/eureka 其中 <username> 为安全校验的用户名；<password> 为该用户的密码
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/