server:
  port: 8762
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin123
spring:
  application:
    name: eureka-server
logging:
  level.root: info
  path: D:/logs/
  file: ${spring.application.name}.log
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/