server:
  port: 90001
spring:
    redis: 
      host: 192.168.71.3 
      port: 6379 
      password: 
      pool: 
        max-active: 8 
        max-idle: 8 
        min-idle: 0 
        max-wait: 10000 
