spring:
  application:
    name: study
  profiles: peer2
server:
  port: 8001
eureka:
  instance:
    hostname: peer2
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
    fetch-registry: true
    register-with-eureka: true