server:
  port: 8083
spring:
  application:
    name: web-admin
  # 指定静态资源的路径
  resources:
    static-locations: classpath:/static/,classpath:/views/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
    hystrix:
        enabled: true     
